spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:sqlite:delivery-dev.db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    root: INFO
    com.ordermanagement: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
