spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:sqlite:delivery.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      platform: sqlite
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.delivery: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
