spring:
  application:
    name: order-management-service
  datasource:
    url: jdbc:sqlite:orders.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        jdbc:
          fetch_size: 50
        generate_statistics: true
  sql:
    init:
      mode: always
      platform: sqlite
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  file:
    name: ./logs/order-management-service.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.ordermanagement: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
